version: "3.8"

services:
  freeswitch:
    build: .
    container_name: freeswitch
    restart: unless-stopped
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5061:5061/tcp"
      - "5061:5061/udp"
      - "8021:8021/tcp"
      - "16384-16500:16384-16500/udp"
    environment:
      - SIP_IP=69.62.85.128
